runtime: nodejs14

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'postgres'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'password'
  INSTANCE_CONNECTION_NAME: 'molten-castle-427004-h5:asia-southeast2:strapi'
  GCS_BUCKET_NAME: 'strapi-manda-cms-gcp'
  GCS_BASE_PATH: 'cms'

beta_settings:
  cloud_sql_instances: 'molten-castle-427004-h5:asia-southeast2:strapi'
